name: 'lego-set'

on:
  workflow_dispatch:
    inputs:
      setNumber:
        description: 'Set number'
        required: true
        type: string
      wishlist:
        description: 'Should be on wishlist'
        required: false
        type: boolean
        default: false

jobs:
  add-lego-set:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --dev]

      - name: Fetch set data
        env:
          REBRICKABLE_API: ${{ secrets.REBRICKABLE_API }}
        id: fetch-set
        run: |
          node ./add-lego-set.js ${{ inputs.setNumber }} ${{ inputs.wishlist }}
        working-directory: './tools'

      - name: Commit and push
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Add ${{ steps.fetch-set.outputs.collection }} ${{ steps.fetch-set.outputs.setName }} (${{ inputs.setNumber }})"
          git push
        working-directory: ./src/content
