name: 'lego-set'

on:
  workflow_dispatch:
    inputs:
      setNumber:
        description: 'Set number'
        required: true
        type: string
      wishlist:
        description: 'Should be on wishlist'
        required: false
        type: boolean
        default: false

jobs:
  add-lego-set:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Prepare pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies with pnpm
        run: pnpm install --frozen-lockfile --dev

      - name: Fetch set data
        env:
          REBRICKABLE_API: ${{ secrets.REBRICKABLE_API }}
        id: fetch-set
        run: |
          node ./add-lego-set.js ${{ inputs.setNumber }} ${{ inputs.wishlist }}
        working-directory: './tools'

      - name: Commit and push
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Add ${{ steps.fetch-set.outputs.collection }} ${{ steps.fetch-set.outputs.setName }} (${{ inputs.setNumber }})"
          git push
        working-directory: ./src/content
